package org.streamrune.core.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Unique identifier for a single persisted event, generated by {@link
 * org.streamrune.core.IdGenerator}.
 */
public record EventId(@JsonValue String value) {

  @JsonCreator
  public EventId {
    if (value == null || value.isBlank()) {
      throw new IllegalArgumentException("eventId is required");
    }
  }

  public static EventId of(String value) {
    return new EventId(value);
  }

  @Override
  public String toString() {
    return value;
  }
}
